services:

  db:
    image: postgres:latest
    ports:
      - "5433:5432"

    restart: always
    environment:
      POSTGRES_PASSWORD: myContainer
    volumes:
      - ./postgres-data:/var/lib/postgresql